#!/usr/bin/env bash
# =============================================================
#  KeralaKart Demo — Stage 01 MVP
#  File   : deploy/02-deploy-frontend.sh
#  Purpose: Deploy the HTML/JS frontend to App Service.
#  Run on : Azure Cloud Shell (Bash)
#
#  What it does:
#    1. Reads the Function App URL from Azure
#    2. Writes config.js with that URL into the public/ folder
#    3. Deploys the public/ folder to App Service via az webapp up
# =============================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../config/00-config.sh"

FRONTEND_DIR="${SCRIPT_DIR}/../app/frontend/public"

info() { echo ""; echo "▶  $*"; }
ok()   { echo "   ✓  $*"; }

# ── Resolve Subscription ──────────────────────────────────────
if [[ -z "${SUBSCRIPTION_ID}" ]]; then
  SUBSCRIPTION_ID=$(az account show --query id -o tsv)
fi
az account set --subscription "${SUBSCRIPTION_ID}"

# ── Step 1: Get the Function App URL ─────────────────────────
info "Resolving Function App URL..."
FUNC_URL="https://${FUNC_NAME}.azurewebsites.net"
ok "API URL: ${FUNC_URL}"

# ── Step 2: Write config.js ───────────────────────────────────
info "Writing config.js..."
cat > "${FRONTEND_DIR}/config.js" <<EOF
// Auto-generated by deploy/02-deploy-frontend.sh — do not commit.
window.API_BASE_URL = "${FUNC_URL}";
EOF
ok "config.js → ${FRONTEND_DIR}/config.js"

# ── Step 3: Deploy to App Service ────────────────────────────
info "Deploying frontend to ${WEBAPP_NAME}..."
cd "${FRONTEND_DIR}"

az webapp up \
  --name           "${WEBAPP_NAME}" \
  --resource-group "${RG}" \
  --os-type        Linux \
  --html

ok "Frontend deployed"
echo ""
echo "   ✅  Open in browser: https://${WEBAPP_NAME}.azurewebsites.net"
echo ""
echo "   Next step: bash deploy/03-deploy-api.sh"
echo ""
